name: MCU Code

on: [push]

env: 
  mcu_id: "0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build "download"
        run: pio run --project-dir ./MCU_code/PlatformIO_code/download

      - name: Build "worker_code"
        run: pio run --project-dir ./MCU_code/PlatformIO_code/worker_code
